### ISSUE TITLE
How to get version 1.6 of certbot? Snap lists 1.32 as latest.

### ISSUE THREAD

**Issue by acesuares** [VojtechMyslivec/letsencrypt-zimbra#82] opened 2022-12-12 12:22 UTC
How to get version 1.6 of certbot? Snap lists 1.32 as latest.

**Comment by VojtechMyslivec** [comment] 2022-12-12 13:13
Hello,

*certbot version 1.6* is the minimum version needed for letsencrypt-zimbra to work. I hope it is clearly noted in the [README](https://github.com/VojtechMyslivec/letsencrypt-zimbra#requirements).

I am not aware of any breaking changes in the certbot, so 1.32 should work well.

V.

**Comment by acesuares** [comment] 2022-12-15 16:27
You're totally right. I misread 1.32 as 1.3.2 but the resaon is, that I am getting this error:
```
letsencrypt-zimbra.sh: error: The certificate cannot be obtained with '/usr/bin/certbot' tool.
```

**Comment by VojtechMyslivec** [comment] 2022-12-16 16:36
I see.

You can use `-v` option to enable _verbose_ output of `letsencrypt-zimbra`. However, if your `certbot` version is 1.3.2, the problem is in old non-supported version of `certbot`.

I don't use _snap_ so I am not sure why it does not list any newer version. What OS and what version do you use? Have you searched your OS packages (apt/rpm) or tried to install it via `pip`?

**Comment by acesuares** [comment] 2022-12-16 21:23
It's my fault, probably. The version is 1.32 and that is higher than 1.6, so that's not the problem. I think i installed a firewall that blocked port 80 and thus made it impossible to get the certificate.

**Comment by acesuares** [comment] 2022-12-16 21:24
Oh BTW this has worked for years without flaws, thank you very much for writing this script!

**Comment by acesuares** [comment] 2022-12-17 11:38
Yep, the blocked port 80 was the problem.

**Comment by VojtechMyslivec** [comment] 2022-12-17 23:19
> Oh BTW this has worked for years without flaws, thank you very much for writing this script!

nice to hear that :+1: :blush: 

> Yep, the blocked port 80 was the problem.

Perfect! I will close the issue then.

**Closed as completed by VojtechMyslivec** 2022-12-17 23:19 UTC
Labels: question
